version: '3.9'

services:
  nginx:
    image: nginx:latest
    container_name: nginx-tester 
    ports:
      - "8080:80"
    volumes:
      - ./config/default.conf:/etc/nginx/nginx.conf:ro
      - ./www:/usr/share/nginx/html:ro
    restart: unless-stopped
